### ISSUE TITLE
What about the Dotty blog?

### ISSUE THREAD

**Issue by TheElectronWill** [lampepfl/scala3doc#160]
Scala3doc will eventually generate dotty.epfl.ch instead of dottydoc.
The website has a blog, which we ignore for now. What should we do with it?

I see several options:
- provide full templating support
    - is it what a doctool is supposed to do?
    - if yes, by what means? Should we go with liquid/handlebar/etc. templates [like we do now with liqp*](https://github.com/lampepfl/scala3doc/blob/master/dokkaJavaApi/src/main/kotlin/com/virtuslab/dokka/site/templates.kt#L39)? We could also build something else based on string interpolation. \<insert another solution here\>
- make a kind of plugin for the blog, separated from the "core" of scala3doc
- use another tool to generate a website for the blog

*: for the normal markdown docs I think we could remove them, especially since the markdown library has a [macro extension](https://github.com/vsch/flexmark-java/wiki/Macros-Extension).

**Comment by abgruszecki** [comment]
@romanowski already has some ideas about how to add templating support to Scala3doc.

From my perspective, I'd like to keep our templating support as orthogonal to the rest of the functionality as possible, because I think that an external Markdown-to-Markdown emplating engine is simply in a better position than us to do a good job of supporting templating well. I'd also say that even if we would integrate with a specific templating engine, we probably wouldn't really gain anything significant.

That being said, I'm not opposed to supporting some templating engine out-of-the-box - I'd just like to be able to easily swap the templating engine without a loss of functionality. We should still be able to resolve doc links in Markdown, for instance.

We should take a look at what functionality the blog exactly needs and consider our options afterwards. I'm not sure if it needs much more than being able to automatically generate the list of blog posts, and if that's the case, we could even do that with a custom-made script in the Dotty repo.

**Comment by TheElectronWill** [comment]
> We should take a look at what functionality the blog exactly needs and consider our options afterwards. I'm not sure if it needs much more than being able to automatically generate the list of blog posts, and if that's the case, we could even do that with a custom-made script in the Dotty repo.

I think it needs the list + a way to extract some metadata (date and author) from the yaml front matter and show it somewhere in the page.

**Comment by romanowski** [comment]
in https://github.com/lampepfl/dotty/pull/10320 we've introduce similar suppor for blogs as dotty-doc does. We are using Liquid templates (and I think it can stay that way). For now it should be sufficient.

In longer terms I think we should take another look at our desing, simpify and polish apis, domcument and add tests for blog-related support.

I think we can reuse that issue to track the productionalization of blogpost support.
