### ISSUE TITLE
Generated diagrams may be really wide

### ISSUE THREAD

**Issue by romanowski** [lampepfl/scala3doc#249]
Maybe we can set a maximum width when it is get rendered? Or zoom out? and provide e.g. hoovers in such case?
![Screenshot from 2020-11-18 20-04-11](https://user-images.githubusercontent.com/3967938/99592165-1c61e680-29f0-11eb-9481-29d72a35d98d.png)

**Comment by BarkingBad** [comment]
What do you mean by `hoovers`? I can try to automatically zoom out and center the diagram to fit the box.

**Comment by romanowski** [comment]
I wondered if we can use hoover to display className when diagram is really small. But this is one of many solution to this problem.

**Comment by BarkingBad** [comment]
Well, the case is, you can zoom in and out any time you want to. I don't know whether there is way to set maximum width, But that won't help much since nodes will have to be spread vertically to fit the diagram and their amount will remain the same. I can try to attach hover with classname, however, I think still most useful way to browse diagram is zooming in and out for parts you want to focus on
